# Generated by Django 5.0.4 on 2024-04-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_rename_react_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='employee',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='department',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='num_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
