# Generated by Django 5.0.4 on 2024-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0003_rename_employee_property_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(default='Rent', max_length=255),
        ),
    ]
